# fly.toml app configuration file generated for resume-ai-backend-silent-firefly-1090 on 2025-05-08T23:37:00+05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'resume-ai-backend-silent-firefly-1090'
primary_region = 'sin'

[build]
  dockerfile = 'Dockerfile'

[env]
  NODE_ENV = 'production'
  PORT = '5000'

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
