# fly.toml app configuration file for resume-ai-backend-silent-firefly-1090
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'resume-ai-backend-silent-firefly-1090'
primary_region = 'sin'

[build]
  dockerfile = 'Dockerfile'

[env]
  NODE_ENV = 'production'
  PORT = '5000'

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
  
  [http_service.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 500

# Updated CORS configuration with X-Requested-With header
[[http_service.cors]]
    allowed_origins = [
      "http://localhost:5173",
      "http://localhost:3000",
      "https://resume-ai-dep.vercel.app",
      "https://resume-ai-dep-git-main-hammadmals-projects.vercel.app",
      "https://resume-ai-553fj7xs0-hammadmals-projects.vercel.app"
    ]
    allowed_methods = ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
    allowed_headers = ["Content-Type", "Authorization", "X-Requested-With"]
    exposed_headers = ["Content-Length", "X-Request-Id"]
    allow_credentials = true
    max_age = 86400

# Add HTTP headers directly
[[http_service.http_headers]]
  for = "/*"
  [http_service.http_headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Strict-Transport-Security = "max-age=15552000; includeSubDomains"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1