name: Keep App Warm

on:
  schedule:
    - cron: '*/15 * * * *'  # Runs every 15 minutes

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping application
        run: |
          # Try to hit the root endpoint first, then fallback to others
          curl -s https://resume-ai-backend-silent-firefly-1090.fly.dev/ || \
          curl -s https://resume-ai-backend-silent-firefly-1090.fly.dev/health || \
          curl -s https://resume-ai-backend-silent-firefly-1090.fly.dev/api || true